"""add importance_score instructions claude_prompt to tasks

Revision ID: 2e90937192ea
Revises: 6981c2715781
Create Date: 2026-04-15 12:12:17.729850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e90937192ea'
down_revision: Union[str, None] = '6981c2715781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('importance_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('claude_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'claude_prompt')
    op.drop_column('tasks', 'instructions')
    op.drop_column('tasks', 'importance_score')
    # ### end Alembic commands ###
